name: Deploy

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  deploy-info:
    runs-on: ubuntu-latest
    steps:
      - name: Get release info
        id: release_info
        uses: actions/github-script@v6
        with:
          script: |
            const { data: release } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const { data: tag } = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/${release.tag_name}`
            });

            const wasPublished = tag.object.sha === release.target_commitish;
            const wasReleased = context.sha tag.object.sha;

            console.log(`Release: ${release.tag_name}`);
            console.log(`Commit: ${tag.object.sha}`);
            console.log(`Published: ${wasPublished}`);
            console.log(`Released: ${wasReleased}`);

            return {
              tag_name: release.tag_name,
              commit_sha: tag.object.sha
            }
      - name: Print release info
        run: |
          echo "Release tag: ${{ toJSON(steps.release_info.outputs) }}"
