name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: environment
        default: 'qual'
      tag_name:
        description: 'The tag name to deploy'
        required: true
        type: string
        default: 'latest'
      commit_sha:
        description: 'The commit sha to deploy'
        required: true
        type: string
        default: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commit_sha }}
      - name: Deploy to ${{ inputs.environment }}
        run: |
          # Deploy to ${{ inputs.environment }}
